version: '3.8'

services:
  neo4j:
    image: s34n/neo4j-img
    ports:
    - '7474:7474'
    - '7473:7473'
    - '7687:7687'
    environment:
    - NEO4J_AUTH=neo4j/neo4spring_cloud
      #    healthcheck: 
      #      test: ["CMD", "curl", "-f", "http://10.133.33.126:7474"]
      #      interval: 90s
      #      timeout: 10s
      #      retries: 3
    networks:
    - service_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

# AMQP Port: 5672
  rabbitmq:
    image: s34n/rmq-img
    ports:
    - '15671:15671'
    - '15672:15672'
    - '5672:5672'
    - '25672:25672'
      #environment:
      #RABBITMQ_DEFAULT_USER: admin
      #RABBITMQ_DEFAULT_PASS: admin
      #    healthcheck:
      #      test: ['CMD', 'curl', '-f', 'http://10.133.33.126:15672']
      #      interval: 30s
      #      timeout: 10s
      #      retries: 3
    networks:
    - service_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  zipkin:
    image: s34n/zipkin-img
    ports:
    - '9410:9410'
    - '9411:9411'
    networks:
    - service_net
    environment:
    - ZIPKIN_LOG_LEVEL=DEBUG
    - RABBIT_URI=amqp://admin:admin@198.13.51.15:5672
    depends_on:
    - rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  eureka:
    image: s34n/eureka-img:1.0.3
    ports:
    - '8001:8001'
    networks:
    - service_net
    environment:
      EUREKA_INSTANCE_HOSTNAME: 198.13.51.15
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/actuator/health"]
      interval: 60s
      timeout: 10s
      retries: 3

  config:
    image: s34n/config-img:1.0.2
    ports:
    - '8002:8002'
    networks:
    - service_net
    environment:
      EUREKA_INSTANCE_HOSTNAME: 198.13.51.15
      SPRING_RABBITMQ_HOST: 198.13.51.15
      SPRING_ZIPKIN_BASE-URL: http://198.13.51.15:9411
    depends_on:
    - eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  leader-data:
    image: s34n/leader-data-img:1.0.4
    ports:
    - '8003:8003'
    networks:
    - service_net
    environment:
      EUREKA_INSTANCE_HOSTNAME: 198.13.51.15
#      SPRING_RABBITMQ_HOST: 10.133.33.126
#      SPRING_ZIPKIN_BASE-URL: 'http://10.133.33.126:9411/'
      SPRING_CLOUD_CONFIG_URI: http://198.13.51.15:8002/
    depends_on:
    - neo4j
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  leaderboard:
    image: s34n/leaderboard-img:1.0.2
    ports:
    - '8004:8004'
    networks:
    - service_net
    environment:
      EUREKA_INSTANCE_HOSTNAME: 198.13.51.15
      SPRING_RABBITMQ_HOST: 198.13.51.15
      SPRING_ZIPKIN_BASE-URL: http://198.13.51.15:9411/
      SPRING_CLOUD_CONFIG_URI: http://198.13.51.15:8002/
    depends_on:
    - leader-data
    - config
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        #    healthcheck:
        #      test: ["CMD", "curl", "-f", "http://localhost:8004/actuator/health"]
        #      interval: 90s
        #      timeout: 10s
        #      retries: 3

  zuul:
    image: s34n/zuul-img:1.0.2
    ports:
    - '8005:8005'
    networks:
    - service_net
    - api_gateway_net
    environment:
      EUREKA_INSTANCE_HOSTNAME: 198.13.51.15
      SPRING_RABBITMQ_HOST: 198.13.51.15
      SPRING_ZIPKIN_BASE-URL: http://198.13.51.15:9411/
      SPRING_CLOUD_CONFIG_URI: http://198.13.51.15:8002/
    depends_on:
    - leaderboard
    - game
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  game:
    image: s34n/game-img:1.0.2
    ports:
    - '8006:8006'
    networks:
    - service_net
    environment:
      EUREKA_INSTANCE_HOSTNAME: 198.13.51.15
      SPRING_RABBITMQ_HOST: 198.13.51.15
      SPRING_ZIPKIN_BASE-URL: http://198.13.51.15:9411/
      SPRING_CLOUD_CONFIG_URI: http://198.13.51.15:8002/
    depends_on:
    - config
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  turbine:
    image: s34n/turbine-img:1.0.2
    ports:
    - '8007:8007'
    networks:
    - service_net
    depends_on:
    - leaderboard
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3


  sciroc:
    image: s34n/sciroc-img:1.0.2
    ports:
    - '80:8000'
    networks:
    - api_gateway_net
    depends_on:
    - zuul
    deploy:
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  service_net:
    driver: overlay
  api_gateway_net:
    driver: overlay

